INSERT INTO date_components (date_id, category_id)
VALUES
(1, 1), -- Date 1, Category 'Movies'
(1, 2), -- Date 1, Category 'Restaurants'
(2, 1), -- Date 2, Category 'Movies'
(2, 3), -- Date 2, Category 'Events'
(3, 1), -- Date 3, Category 'Movies'
(3, 4), -- Date 3, Category 'Activities'
(4, 2), -- Date 4, Category 'Restaurants'
(4, 3), -- Date 4, Category 'Events'
(5, 2), -- Date 5, Category 'Restaurants'
(5, 4), -- Date 5, Category 'Activities'
(6, 3), -- Date 6, Category 'Events'
(6, 4), -- Date 6, Category 'Activities'
(7, 1), -- Date 7, Category 'Movies'
(7, 2), -- Date 7, Category 'Restaurants'
(8, 3), -- Date 8, Category 'Events'
(8, 4), -- Date 8, Category 'Activities'
(9, 1), -- Date 9, Category 'Movies'
(9, 4), -- Date 9, Category 'Activities'
(10, 2), -- Date 10, Category 'Restaurants'
(10, 3), -- Date 10, Category 'Events'
(11, 1), -- Date 11, Category 'Movies'
(11, 2), -- Date 11, Category 'Restaurants'
(12, 3), -- Date 12, Category 'Events'
(12, 4), -- Date 12, Category 'Activities'
(13, 1), -- Date 13, Category 'Movies'
(13, 3), -- Date 13, Category 'Events'
(14, 2), -- Date 14, Category 'Restaurants'
(14, 4), -- Date 14, Category 'Activities'
(15, 3), -- Date 15, Category 'Events'
(15, 4), -- Date 15, Category 'Activities'
(16, 1), -- Date 16, Category 'Movies'
(16, 2); -- Date 16, Category 'Restaurants'



