INSERT INTO movies (category_id, component_id, movie_title, start_time, duration, movie_theatre, synopsis, photo_url, address, movie_url)
VALUES 
(1, 1, 'Inception', '18:00:00', 150, 'Toronto Cinema', 'Dom Cobb (Leonardo DiCaprio) is a thief with the rare ability to enter peoples dreams and steal their secrets from their subconscious. His skill has made him a hot commodity in the world of corporate espionage but has also cost him everything he loves.', 'https://i.ebayimg.com/images/g/N84AAOSwYGFUwoNk/s-l1600.jpg', '123 Main St, Toronto', 'https://en.wikipedia.org/wiki/Inception'),
(1, 3, 'Spider-Man: No Way Home', '20:00:00', 140, 'Downtown Theater', 'With Spider-Mans identity now revealed, our friendly neighborhood web-slinger is unmasked and no longer able to separate his normal life as Peter Parker from the high stakes of being a superhero. When Peter asks for help from Doctor Strange, the stakes become even more dangerous, forcing him to discover what it truly means to be Spider-Man.', 'https://i.ebayimg.com/images/g/N~UAAOSwFfFkPNPv/s-l1200.webp', '456 King St, Toronto', 'https://en.wikipedia.org/wiki/Spider-Man:_No_Way_Home'),
(1, 5, 'Dune', '16:30:00', 155, 'Cityplex Cinema', 'Paul Atreides, a brilliant and gifted young man born into a great destiny beyond his understanding, must travel to the most dangerous planet in the universe to ensure the future of his family and his people. As malevolent forces explode into conflict over the planets exclusive supply of the most precious resource in existence, only those who can conquer their own fear will survive.', 'https://i.ebayimg.com/images/g/JJsAAOSw1UphNb-p/s-l1600.jpg', '789 Queen St, Toronto', 'https://en.wikipedia.org/wiki/Dune_(2021_film)'),
(1, 13, 'Elemental', '19:45:00', 142, 'Riverview Theater', 'In a city where fire, water, land, and air residents live together, a fiery young woman and a go-with-the-flow guy discover something elemental: how much they actually have in common.', 'https://i.etsystatic.com/25432943/r/il/0b0319/5015973239/il_570xN.5015973239_8adn.jpg', '567 Elm St, Toronto', 'https://en.wikipedia.org/wiki/Elemental_(2023_film)'),
(1, 17, 'The Dark Knight', '21:15:00', 152, 'Gotham City Cinemas', 'With the help of allies Lt. Jim Gordon (Gary Oldman) and DA Harvey Dent (Aaron Eckhart), Batman (Christian Bale) has been able to keep a tight lid on crime in Gotham City. But when a vile young criminal calling himself the Joker (Heath Ledger) suddenly throws the town into chaos, the caped Crusader begins to tread a fine line between heroism and vigilantism.', 'https://m.media-amazon.com/images/M/MV5BMTMxNTMwODM0NF5BMl5BanBnXkFtZTcwODAyMTk2Mw@@._V1_.jpg', '890 Oak St, Toronto', 'https://en.wikipedia.org/wiki/The_Dark_Knight'),
(1, 21, 'Barbie', '15:00:00', 114, 'Bubba Gump Cinema', 'Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.', 'https://i.ebayimg.com/images/g/lzMAAOSwDMRkxPxb/s-l1200.webp', '234 Pine St, Toronto', 'https://en.wikipedia.org/wiki/Barbie_(film)'), 
(1, 25, 'Everything Everywhere All at Once', '22:30:00', 175, 'Corleone Theater', 'When an interdimensional rupture unravels reality, an unlikely hero must channel her newfound powers to fight bizarre and bewildering dangers from the multiverse as the fate of the world hangs in the balance.', 'https://i.ebayimg.com/images/g/9~UAAOSwRahjstNq/s-l1600.jpg', '678 Maple St, Toronto', 'https://en.wikipedia.org/wiki/Everything_Everywhere_All_at_Once'),
(1, 31, 'The Super Mario Bros. Movie', '17:45:00', 127, 'Dinoplex Theater', 'While working underground to fix a water main, Brooklyn plumbers and brothers Mario and Luigi are transported through a mysterious pipe to a magical new world. But when the siblings are separated, an epic adventure begins.', 'https://i.ebayimg.com/images/g/XAkAAOSwP2FkNWl6/s-l1600.jpg', '901 Birch St, Toronto', 'https://en.wikipedia.org/wiki/The_Super_Mario_Bros._Movie');